name: Build Electron App

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, macos-latest]

    steps:
      - name: Check out git repository
        uses: actions/checkout@v4 # v3 -> v4로 변경

      - name: Install Node.js
        uses: actions/setup-node@v4 # v3 -> v4로 변경
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Build and Package for Windows
        if: runner.os == 'Windows' # 이 작업은 Windows Runner에서만 실행
        run: npm run package:win
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Package for macOS
        if: runner.os == 'macOS' # 이 작업은 macOS Runner에서만 실행
        run: npm run package:mac
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4 # v3 -> v4로 변경 (가장 중요한 수정)
        with:
          name: ${{ matrix.os }}-build
          path: dist