# File: .github/workflows/release.yml

name: Release

on:
  push:
    tags:
      - 'v*' # v1.0.0, v1.2.3 등 'v'로 시작하는 태그가 푸시될 때만 실행

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      # ▼▼▼ [핵심 수정 1] React 앱 빌드 단계를 분리 ▼▼▼
      - name: Build React App
        env:
          NODE_OPTIONS: "--max-old-space-size=4096" # 빌드 시에도 메모리 할당
          CI: true # 경고를 오류로 처리하도록 명시 (기본값이지만 확실히 함)
        run: npm run build

      # ▼▼▼ [핵심 수정 2] Electron 패키징 및 릴리즈 단계를 분리 ▼▼▼
      - name: Package and Release Application
        env:
          NODE_OPTIONS: "--max-old-space-size=4096" # 패키징 시에도 메모리 할당
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: electron-builder --publish always