# File: .github/workflows/release.yml

name: Release

on:
  push:
    tags:
      - 'v*' # v1.0.0, v1.2.3 등 'v'로 시작하는 태그가 푸시될 때만 실행

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        env:
          NODE_OPTIONS: "--max-old-space-size=4096"
        run: npm ci

      - name: Build React App
        env:
          NODE_OPTIONS: "--max-old-space-size=4096"
          CI: true
        run: npm run build

      - name: Package and Release Application
        env:
          NODE_OPTIONS: "--max-old-space-size=4096"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # ▼▼▼ [핵심 수정] npx를 사용하여 electron-builder 실행 ▼▼▼
        run: npx electron-builder --win --mac --publish always